=== RunnerPyzza/RunnerPyzza/RunnerPyzza/ClientCommon/xsd/MachinesSetup.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
          targetNamespace="RunnerPyzza"
          xmlns="RunnerPyzza" 
          elementFormDefault="qualified">
  <xs:element name="machinesSetup">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="machine" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:whiteSpace value="preserve"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="hostname" type="xs:string"/>
              <xs:element name="user" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RunnerPyzza/RunnerPyzza/EmilioMachine.xml
<?xml version="1.0" encoding="UTF-8"?>

<machinesSetup xmlns="RunnerPyzza"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="RunnerPyzza MachinesSetup.xsd">
  <machine>
    <name>isaac</name>
    <hostname>isaac</hostname>
    <user>potenzae</user>
  </machine>
  <machine>
    <name>isaac</name>
    <hostname>isaac</hostname>
    <user>potenzae</user>
  </machine>
</machinesSetup>

=== RunnerPyzza/RunnerPyzza/GalaMachine.xml
<?xml version="1.0" encoding="UTF-8"?>

<machinesSetup xmlns="RunnerPyzza"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="RunnerPyzza MachinesSetup.xsd">
  <machine>
    <name>bazzilab</name>
    <hostname>150.217.45.168</hostname>
    <user>mgalardini</user>
  </machine>
  <machine>
    <name>galactus</name>
    <hostname>galactus-mobile</hostname>
    <user>galactus</user>
  </machine>
</machinesSetup>
